// frontend/src/components/Footer.svelte
<button
  on:click={() => {
    // TODO : Open Help Modal
  }}
  class="help-btn">Help &#128161;</button
>
<footer>
  <p>
    Maintained by <strong
      ><a target="_blank" href="https://metakgp.github.io/">MetaKGP</a></strong
    >
    with
    <strong>❤️</strong>
    at
    <a target="_blank" href="https://github.com/metakgp/gyft"
      ><strong>Github</strong></a
    >
  </p>
</footer>

<style>
  .help-btn {
    border: none;
    width: fit-content;
    padding: 0.5rem 1rem;
    font-size: 1rem;
    border-radius: 8px;
    color: white;
    font-weight: bold;
    background-color: #989898;
    box-shadow: none;
    margin-bottom: 1rem;
    cursor: pointer;
  }
  a {
    color: inherit;
  }
</style>

// frontend/src/components/Footer.tsx
import React from "react";
import { useAppContext } from "../AppContext/AppContext";
type props = {
    openModal: React.Dispatch<React.SetStateAction<boolean>>;
};
const Footer: React.FC<props> = ({ openModal }) => {
    const { logout, user } = useAppContext();

    return (
        <div>
            <div className="help">
                <button className="help-button" onClick={() => openModal(true)}>
                    Help 💡
                </button>
                {user.ssoToken && (
                    <button onClick={logout} className="logout-button">
                        Logout
                    </button>
                )}
            </div>
            <footer>
                <p>
                    Contribute to this project on{" "}
                    <strong>
                        <a
                            href="https://github.com/metakgp/gyft"
                            target="_blank"
                        >
                            GitHub
                        </a>
                    </strong>{" "}
                    | Powered by{" "}
                    <strong>
                        <a target="_blank" href="https://metakgp.github.io/">
                            <span className="metakgp">MetaKGP</span>
                        </a>
                    </strong>{" "}
                    with ❤️
                </p>
            </footer>
        </div>
    );
};

export default Footer;
